import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { SOURCE_BADGE_CLASS_KO } from "../../constants/source";
import { extractTextFromSummary } from "../../utils/summary";
import type { CartoonItem } from "../../types/news";
import SimpleComicPanel from "./SimpleComicPanel";

interface CartoonCardProps {
  item: CartoonItem;
  highlight: boolean;
}

export default function CartoonCard({ item, highlight }: CartoonCardProps) {
  const cardRef = useRef<HTMLDivElement>(null);
  const [isVisible, setIsVisible] = useState(highlight);

  useEffect(() => {
    if (highlight && cardRef.current) {
      const timer = setTimeout(() => {
        cardRef.current?.scrollIntoView({
          behavior: "smooth",
          block: "center",
        });
      }, 300);
      return () => clearTimeout(timer);
    }
  }, [highlight]);

  useEffect(() => {
    const currentRef = cardRef.current;
    if (!currentRef) return;

    const observer = new IntersectionObserver(
      (entries) => {
        if (entries[0].isIntersecting) {
          setIsVisible(true);
          observer.unobserve(currentRef);
        }
      },
      { threshold: 0.08, rootMargin: "0px 0px -40px 0px" },
    );
    observer.observe(currentRef);
    return () => {
      observer.disconnect();
    };
  }, []);

  const dateStr = item.published_at
    ? new Date(item.published_at).toLocaleDateString("ko-KR", {
        year: "numeric",
        month: "long",
        day: "numeric",
      })
    : "";

  const badgeClass =
    item.source && SOURCE_BADGE_CLASS_KO[item.source]
      ? SOURCE_BADGE_CLASS_KO[item.source]
      : "badge-default";

  return (
    <article
      ref={cardRef}
      id={`comic-${item.news_id}`}
      className={`overflow-hidden bg-white transition-all duration-700 ease-[cubic-bezier(0.22,1,0.36,1)] rounded-[28px] ${
        highlight
          ? "border-2 border-[#FBBF24] shadow-[0_0_0_6px_rgba(251,191,36,0.12),_0_16px_56px_rgba(22,19,17,0.18)]"
          : "border border-[#E4DDD3] shadow-[0_6px_32px_rgba(22,19,17,0.1)]"
      } ${isVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-12"}`}
    >
      {/* 카드 헤더 (dark) */}
      <div className="bg-[#141210]">
        {/* 상단 메타 스트립 */}
        <div className="flex items-center justify-between px-6 pt-5 pb-4 border-b border-white/6">
          <div className="flex items-center gap-2.5">
            <span className={`${badgeClass} text-[10px] font-black px-3 py-1.5 rounded-full`}>
              {item.source || "NEWS"}
            </span>
            <span className="text-[11px] font-medium font-sans text-white/28">
              {dateStr}
            </span>
          </div>
          <div className="flex items-center gap-1.5">
            <div className="w-1.5 h-1.5 rounded-full animate-pulse bg-[#FBBF24]" />
            <span className="text-[9px] font-black uppercase text-white/22 tracking-[0.22em]">
              AI COMIC
            </span>
          </div>
        </div>

        {/* 제목 + 요약 + 링크 */}
        <div className="px-6 pt-5 pb-6">
          <h2
            className="font-black text-white leading-snug break-keep mb-3 font-serif text-[clamp(17px,3vw,23px)] tracking-[-0.01em]"
          >
            {item.title}
          </h2>

          {item.summary && (
            <p className="text-sm leading-relaxed line-clamp-2 mb-5 font-sans text-white/40">
              {extractTextFromSummary(item.summary)}
            </p>
          )}

          <Link
            to={`/news/${item.news_id}`}
            className="inline-flex items-center gap-2 text-[12px] font-black px-4.5 py-2 rounded-full bg-[#FBBF24] text-[#141210] transition-all duration-200 hover:bg-[#F59E0B] hover:-translate-y-[1px] hover:shadow-[0_4px_16px_rgba(251,191,36,0.4)]"
          >
            원본 기사 보기
            <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M17 8l4 4m0 0l-4 4m4-4H3" />
            </svg>
          </Link>
        </div>
      </div>

      {/* 만화 영역 */}
      <div>
        {/* 섹션 타이틀 바 */}
        <div className="flex items-center justify-between px-5 py-2.5 bg-[#FBBF24]">
          <span className="font-black text-[10px] uppercase tracking-[0.18em] text-[#141210]">
            TODAY'S AI NEWS COMIC
          </span>
          <span className="text-[9px] font-bold text-[#141210]/45 tracking-[0.1em]">
            Generated by AI
          </span>
        </div>

        {/* 패널 */}
        {item.comic_urls.length > 0 && (
          <SimpleComicPanel scene={item.comic_urls[0]} />
        )}

        {/* 하단 크레딧 바 */}
        <div className="py-3.5 text-center bg-[#F7F4EF] border-t border-[#E4DDD3]">
          <span className="text-[9px] font-black uppercase text-[#C9C3BA] tracking-[0.2em]">
            AI Comic Engine · 뉴스 정보 나침반
          </span>
        </div>
      </div>
    </article>
  );
}
